spring:
  config:
    import: classpath:application-secrets.yml
  datasource:
    driver-class-name: ${prod.datasource.driver-class-name}
    url: ${prod.datasource.url}
    username: ${prod.datasource.username}
    password: ${prod.datasource.password}


dubbo:
  application:
    # 设置应用的名称
    name: dy-api-admin
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22225
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: ${prod.double.registry.address}
  config-center:
    timeout: 40000

dy:
  gateway:
    host: http://8.130.9.216:8090


server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

