spring:
  application:
    name: dy-api-admin
  # DataSource Config

  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: ${prod.datasource.driver-class-name}
    url: ${prod.datasource.url}
    password: ${prod.datasource.password}
    username: ${prod.datasource.username}
#    driver-class-name: ${default.datasource.driver-class-name}
#    url: ${default.datasource.url}
#    password: ${default.datasource.password}
#    username: ${default.datasource.username}
  config:
    import: classpath:application-secrets.yml

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none
  # redis 配置
  redis:
    port: 6379
    host: 8.130.9.216
    database: 0
server:
  port: 8101
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

dyapi:
  client:
    access-key: dingyu
    secret-key: Hello world

dy:
  gateway:
    host: http://localhost:8090



# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dy-api-admin
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22224
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: ${default.double.registry.address}